import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { SRGentrys } from "../components/SRGentrys";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SRG historical data</title>
        <meta name="description" content="Generated by sunshine" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SRGentrys />
    </div>
  );
};

export default Home;
